name: Update data for 1.r

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs daily at midnight UTC. Adjust as needed.
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true  # Use public RStudio Package Manager for faster package installation
          install-r: true  # Install the latest version of R available

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("DBI", "odbc", "dplyr", "crypto2"))'

      - name: List files in directory (optional for debugging)
        run: |
          ls  # List files in the current directory

      - name: Run R script
        run: |
          Rscript 1_hourly.R
          Rscript 2_hourly.R
          Rscript 3_hourly.R
          Rscript 4_hourly.R
          Rscript 5_hourly.R
          Rscript 6_hourly.R
          Rscript 7_hourly.R
          Rscript 8_hourly.R
          Rscript 9_hourly.R
          Rscript 10_hourly.R
